### ISSUE TITLE
scadipwa stripe-payment version 4 not working in scandipwa5.1

### ISSUE THREAD

**Issue by kpAbbacus** [scandipwa/stripe-payments#5]
i din't get any asyncData in stripe payment, even i try to do all possible sollution but din't get.

**Comment by rudracomputech** [comment]
I am also getting problem with version 4 getting below error

<pre>
formatWebpackMessages.js:116 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (formatWebpackMessages.js:116:1)
    at Module../node_modules/react-dev-utils/formatWebpackMessages.js (formatWebpackMessages.js:116:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object../node_modules/react-dev-utils/webpackHotDevClient.js (webpackHotDevClient.js:22:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object.1 (Stripe.js:50:1)
    at __webpack_require__ (bootstrap:856:1)
    at checkDeferredModules (bootstrap:45:1)
</pre>
Here are my package 
<pre>
 "dependencies": {
        "@scandipwa/eslint-config": "^0.1.12",
        "@scandipwa/paypal": "file:packages/paypal",
        "@cd ../": "^4.1.0",
        "@scandipwa/scandipwa-scripts": "^2.3.8",
        "@scandipwa/stripe-payments": "file:packages/stripe-payments",
        "@tilework/mosaic": "0.1.4",
        "@tilework/mosaic-craco": "^0.0.5",
        "postcss": "8.4.5",
        "workbox-webpack-plugin": "^6.4.2"
    },
</pre>

**Comment by chillpilllike** [comment]
Scandipwa is useless now as not evena. single integration for payment gateway is possible without spending $500. overpriced and clear loot.
